export default Object.freeze({
  ADOPTION_REQUEST: "AdoptionRequest",
  ADOPTION_REQUEST_DETAIL: "AdoptionRequestDetail",
  FORM: "Form",
  FORM_ADOPTION: "FormAdoption",
  HOME: "Inicio",
  REFUGEHOUSE_DETAIL: "RefugeHouseDetail",
  LISTINGREFUGE: "ListingRefuge",
  LOGIN: "Login",
  PET_DETAILS: "PetDetails",
  PROFILE: "Profile",
  REFUGE_HOUSE: "RefugeHouse",
  REGISTER: "Register",
  REGISTER_HOUSE: "RegisterHouse",
});
