export default Object.freeze({
  ADOPTION_REQUEST: "AdoptionRequest",
  ADOPTION_REQUEST_DETAIL: "AdoptionRequestDetail",
  FORM: "Form",
  FORM_ADD_PET: "FormAddPet",
  FORM_ADOPTION: "FormAdoption",
  FORM_CREDIT_CARD: "FormCreditCard",
  HOME: "Inicio",
  HOUSE_PROFILE: "HouseProfile",
  REFUGEHOUSE_DETAIL: "RefugeHouseDetail",
  LISTINGREFUGE: "ListingRefuge",
  LOGIN: "Login",
  PAYMENT: "payment",
  PET_DETAILS: "PetDetails",
  PROFILE: "Profile",
  REFUGE_HOUSE: "RefugeHouse",
  REGISTER: "Register",
  REGISTER_HOUSE: "RegisterHouse",
  VOUCHER: "Voucher",
});
