export default {
  name: "",
  dni: "",
  phone: "",
  email: "",
  address: "",
  city: "",
  country: "",
  province: "",
  petId: 0,
  profileHouseId: 0,
  userId: 0,
  comentary: "",
  hasPets: false,
  whatPet: "",
  why: "",
  timeAlone: "",
  isApproved: false,
  isActive: true,
  isRejected: false,
};
